"""Shared fixture paths. The fixture files themselves are committed,
generated by examples/fixtures/build_fixtures.py -- not regenerated
per test run, same convention Claim Card's synthetic_violations fixture
already follows."""

from __future__ import annotations

from pathlib import Path

import pytest

FIXTURES_DIR = Path(__file__).resolve().parent.parent / "examples" / "fixtures"


@pytest.fixture
def fixtures_dir() -> Path:
    return FIXTURES_DIR
